market_analysis:
  description: >
    对股票 {stock_code}（{company_name}）进行全面的A股市场分析，包括：
    1. 实时行情分析：当前价格、涨跌幅、成交量、技术指标等
    2. 技术形态分析：K线形态、均线系统、支撑阻力位、趋势判断
    3. 资金流向分析：主力资金动向、北向资金、散户资金流向
    4. 板块轮动分析：所属行业板块表现、市场热点分析
    5. 政策面分析：相关行业政策、监管政策影响评估
    重点关注A股市场的特殊性和中国特色的投资环境。

  expected_output: >
    详细的市场分析报告，包括：
    - 实时行情数据和技术指标解读
    - 技术形态和趋势判断
    - 资金流向分析结论
    - 板块轮动和市场热点分析
    - 政策影响评估
    - 短期走势预测和关键关注点
    使用清晰的结构和专业术语，体现A股市场特色。

financial_analysis:
  description: >
    对 {company_name}（{stock_code}）进行深入的财务分析，包括：
    1. 财务比率分析：盈利能力、偿债能力、营运能力、成长能力指标
    2. 财务趋势分析：最近3-5年的财务数据变化趋势
    3. 同业对比分析：与同行业上市公司的关键财务指标对比
    4. 估值分析：PE、PB、PS、PEG等估值指标评估
    5. 财务质量评估：收入质量、利润质量、现金流状况
    6. 风险因素识别：财务风险、经营风险、行业风险等
    重点考虑中国会计准则和A股市场的估值特点。

  expected_output: >
    专业的财务分析报告，包括：
    - 各项财务指标的详细解读和同比环比分析
    - 财务状况的综合评价（优劣势分析）
    - 同业竞争力和行业地位评估
    - 估值水平判断（高估/合理/低估）
    - 财务风险评估和预警
    - 投资价值的财务层面判断
    使用数据支撑分析结论，提供具体的数值对比。

sentiment_analysis:
  description: >
    分析 {company_name}（{stock_code}）的市场情绪状况，包括：
    1. 市场整体情绪：大盘走势、涨跌分布、恐慌贪婪指数
    2. 资金情绪：主力资金流向、北向资金动向、融资融券变化
    3. 新闻舆情：相关新闻、政策消息、市场讨论热度
    4. 投资者情绪：散户情绪、机构观点、分析师评级
    5. 技术情绪：技术指标信号、买卖力道分析
    6. 风险情绪：市场风险偏好、个股风险溢价
    重点分析A股市场的情绪驱动因素和投资者行为特征。

  expected_output: >
    全面市场情绪分析报告，包括：
    - 当前市场情绪状态描述（乐观/悲观/中性）
    - 各类情绪指标的具体分析
    - 情绪驱动因素识别
    - 情绪变化趋势预测
    - 情绪面投资机会和风险提示
    - 基于情绪的交易建议
    体现对A股市场投资者心理的深刻理解。

investment_recommendation:
  description: >
    综合前面的市场分析、财务分析和情绪分析结果，
    为 {company_name}（{stock_code}）提供专业的投资建议：
    1. 投资评级：强烈买入/买入/中性/卖出/强烈卖出
    2. 投资逻辑：综合各方面分析的主要投资理由
    3. 目标价格：6-12个月目标价和预期收益率
    4. 投资策略：建仓策略、持仓策略、止盈止损策略
    5. 风险控制：主要风险识别和应对措施
    6. 时间框架：短期、中期、长期投资建议
    7. 配置建议：在投资组合中的建议配置比例
    考虑A股市场的T+1、涨跌停限制等交易制度特点。

  expected_output: >
    最终投资建议报告，要求：
    - 明确的投资评级和目标价格
    - 详细的投资逻辑分析过程
    - 具体的操作建议和时机选择
    - 完整的风险评估和控制方案
    - 不同时间维度的投资建议
    - 清晰的报告格式和专业表述
    - 为投资者提供可执行的投资决策参考。